### PR TITLE
Ticket #12 - Edit a Category

### PR DESCRIPTION
**Pull request by guacajoely**
# Description

**Completed ticket# 12** in Trello - [Edit a Category]( https://trello.com/c/5KE0IIJB/12-12-edit-a-category)
When you click the “Edit” button (middle pencil icon), you are brought to a form, where you can edit and save the name of a category

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

**GIT this branch:**
1. Clone this repository to your own machine using `git clone https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers.git`
2. `git fetch -a` in the master branch to retrieve this branch named **jd-edit-category.**
3.  checkout this branch using the command `git checkout jd-edit-category`

**Create the database:**
1. Open Visual Studio.
2. At the start screen select "Open a Local Folder"
4. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, then select the SQL folder
5. Run BOTH .sql files in the [SQL folder](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL) (The first file creates the database and tables if they don’t already exist, and the second file inserts a very small amount of sample data into those tables for testing.

**Add dummy data:**
1. In Visual Studio, Open the View menu and select SQL Server Object Explorer.
2. Expand the node for your SQL Server instance.
3. Expand "Databases"  
4. Right-click on the TabloidMVC database and choose New Query.
5. Run this SQL script to add a category for testing named TEST CATEGORY:
`INSERT INTO Category (Name) VALUES ('TEST CATEGORY');`

**Run the app:**
1. Open Visual Studio
2. At the start screen select Open a project or solution.
3. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, and select the .sln file to run the solution.
6. Hit the Green play button on the toolbar that says TabloidMVC.
7. The app should launch by opening up a new window in your default browser.

**Test the new feature:**
1. In the header, next to the Title (Tabloid) there should be a single link to Login, click this.
2. For testing purposes, log in as admin@example.com, and click login.
3. After successfully logging in, you should now see a link to CATEGORIES, click this.
5. When you click on the edit button of any of the categories, it should present you with a form where you can edit and save the name of the category.
6. Try changing "TEST CATEGORY" to "NOT A TEST CATEGORY"
7. After saving a Category’s new name, it should redirect you back to the index and the Category name you just changed should be reflected in the list of categories.

**Note:** The Add New Category, View, and Delete buttons are not functional yet.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Bobbyhughes-17** [comment]
Solid work comrade. Appreciate all your hard work.

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- We want to protect our data so let's include some dummy data when we are changing things
- Create a new SQL query or just add it to the testing instructions with some more categories 
-  Be explicit about which one they should change - for example - please change Cthulhu sightings to Mothman sightings.

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Great job 👼

**Comment by Nic338** [comment]
Good one, nice edits.

**Pull request merged**
