### PR TITLE
Ticket #31 - View Subscribed Posts on Homepage

### PR DESCRIPTION
**Pull request by guacajoely**
# Description

**Completed ticket# 31** in Trello - [View Subscribed Posts on Homepage](https://trello.com/c/eHeXGnhN/31-31-view-subscribed-posts-on-homepage)

While on the home page, a user will now see a list of posts from the authors they have subscribed to.

In addition to adding this functionality, I shifted some of the code in the Index view for Home, altering when elements appear. You only view the "Get Started header" if you are NOT authenticated now, and the "Blogs and Journals" header is only visible if you are logged in. 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

**GIT this branch:**
1. Clone this repository to your own machine using `git clone https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers.git`
2. `git fetch -a` in the master branch to retrieve this branch named **jd-view-subs.**
3.  checkout this branch using the command `git checkout jd-view-subs`

**Create the database:**
1. Open Visual Studio.
2. At the start screen select "Open a Local Folder"
4. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, then select the SQL folder
5. Run BOTH .sql files in the [SQL folder](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL) (The first file creates the database and tables if they don’t already exist, and the second file inserts a very small amount of sample data into those tables for testing.

**Note:**  Please run this SQL query as well to insert a second user and subscribe them to another user's (Admin's) posts:
```
INSERT INTO [UserProfile] (
[FirstName], [LastName], [DisplayName], [Email], [CreateDateTime], [ImageLocation], [UserTypeId], [IsActive])
VALUES ('Stephen', 'Seagull', 'Steve-O', 'test@email.com', SYSDATETIME(), NULL, 2, 1)

INSERT INTO Subscription ( 
SubscriberUserProfileId, ProviderUserProfileId, BeginDateTime, EndDateTime)
VALUES ( 2, 1, SYSDATETIME(), NULL)
```

**Run the app:**
1. Open Visual Studio
2. At the start screen select Open a project or solution.
3. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, and select the .sln file to run the solution.
7. Hit the Green play button on the toolbar that says TabloidMVC.
8. The app should launch by opening up a new window in your default browser.

**Test the new feature:**
1. In the header, next to the Title (Tabloid) there should be a link to Login, click this.
2. For testing purposes, log in as **`test@email.com`**, and click login.
3. After successfully logging in, your home page header that said "Get Started" should now be replaced with one that says "Blogs & Journals" and you should see Admin's Post "C# is the Best Language" listed, since the user we are logged in is subscribed to Admin.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Looks good 👼

**Review by sarahebrooks12 — APPROVED** [review]
Looks good 👼

**Comment by Bobbyhughes-17** [comment]
APPROVED

**Comment by Nic338** [comment]
Works well, nice

**Pull request merged**
