### PR TITLE
Ticket #19 - User can now see the comment list for a specific post

### PR DESCRIPTION
**Pull request by gschryver**
# Description
This is on the `gs-viewpostcomments` branch.

For your reference: [SQL Data](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL)

**Completed Ticket #19** in Trello - [View a Post's Comments](https://trello.com/c/A9X3rQl2)
Per the ticket: "As a reader, I would like to see a list of all the Comments on a Post so that I can read and take part in the discussion on a particular Post." 

This functionality has now been implemented. 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

**GIT this branch:**
1. Clone this repository to your own machine using `git clone https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers.git`
2. `git fetch -a` in the master branch to retrieve this branch named `gs-viewpostcomments`.
3.  checkout this branch using the command `git checkout gs-viewpostcomments`

**Create the database:**
1. Open Visual Studio.
2. At the start screen select "Open a Local Folder"
4. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, then select the SQL folder
5. Run ALL THREE .sql files in the [SQL folder](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL) (The first file creates the database and tables if they don’t already exist, and the second file inserts a very small amount of sample data into those tables for testing. The third file inserts some seed data for the comments).

**Run the app:**
1. Open Visual Studio
2. At the start screen select Open a project or solution.
3. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, and select the .sln file to run the solution.
7. Hit the Green play button on the toolbar that says TabloidMVC.
8. The app should launch by opening up a new window in your default browser.

**Test the new feature:**
1. Click on Log In on the navigation bar. Log in using the user: admin@example.com. 
2. Click on Posts in the navigation bar.
3. You will see a table that includes a post. Click on the "eye" icon on the right-hand side of the table (for Post Details).
4. Once inside of the post details page, you will then click on the comment bubble icon (View Comments), located below the post title, author name, publish date, edit, and delete icons.
5. This will take you to the comment details page. 
6. The table headers should include the information for the following:  
- DisplayName
- Subject
- Content
- CreateDateTime 
7. Under each header, the dummy data should populate the table fields. You should see 'admin' for DisplayName, Subject: Interesting post!, Content: I found this post very enlightening. Thanks for sharing!, and a CreateDateTime for '6/30/2023 1:34:06 PM". 

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- Per the ticket, we should see :
Display the following information for each Comment

Subject
Content
Author's Display Name
Creation date (MM/DD/YYYY)

- We don't need all the headers that's listed just the ones that are stated in the ticket
- We would need some dummy data to be able to see if we can actually see the comments and not just the headers - this is crucial to being able to know if the code is actually working. You can include your own SQL script in your testing instructions. 
- You can either list everything that should be listed with data or with a SQL query

**Review by sarahebrooks12 — APPROVED** [review]
Way better testing instructions! 
Good job on including dummy data and including exactly what to see.
Over explaining is always better than thinking "they know what that is" 
You can always include a SQL query instead of typing everything they should see if you'd like as an example of what the user should be seeing on the website.

**Comment by guacajoely** [comment]
looks good

**Comment by Bobbyhughes-17** [comment]
Super work!

**Comment by Nic338** [comment]
Looks good, good instructions.

**Pull request merged**
