### PR TITLE
Ticket #16 - Edit a Tag

### PR DESCRIPTION
**Pull request by guacajoely**
# Description

**Completed ticket# 16** in Trello - [Edit a Tag](https://trello.com/c/FFIZTPs1/16-16-edit-a-tag)
When you click the “Edit” button (pencil icon), you are brought to a form, where you can edit and save the name of a tag

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

**GIT this branch:**
1. Clone this repository to your own machine using `git clone https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers.git`
2. `git fetch -a` in the master branch to retrieve this branch named **jd-edit-tag.**
3.  checkout this branch using the command `git checkout jd-edit-tag`

**Create the database:**
1. Open Visual Studio.
2. At the start screen select "Open a Local Folder"
4. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, then select the SQL folder
5. Run BOTH .sql files in the [SQL folder](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL) (The first file creates the database and tables if they don’t already exist, and the second file inserts a very small amount of sample data into those tables for testing.

**Check the data**
> 1. In Visual Studio, Open the View menu and select SQL Server Object Explorer.
> 2. Expand the node for your SQL Server instance.
> 3. Expand "Databases"  
> 4. Right-click on the TabloidMVC database and choose New Query.
> 5. Run this SQL script to view the tags in the database:
> `SELECT id, name FROM Tag order by Name;`

**Run the app:**
1. Open Visual Studio
2. At the start screen select Open a project or solution.
3. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, and select the .sln file to run the solution.
7. Hit the Green play button on the toolbar that says TabloidMVC.
8. The app should launch by opening up a new window in your default browser.

**Test the new feature:**
1. In the header, next to the Title (Tabloid) there should be a single link to Login, click this.
2. For testing purposes, log in as admin@example.com, and click login.
3. After successfully logging in, you should now see a link to TAGS, click this.
4. First, ADD a new tag by clicking Add New Tag at the top of the index and name it "ANOTHER TEST TAG"

alternatively, you can add a tag to test deletion with an SQL query following these instructions:

> 1. In Visual Studio, Open the View menu and select SQL Server Object Explorer.
> 2. Expand the node for your SQL Server instance.
> 3. Expand "Databases"  
> 4. Right-click on the TabloidMVC database and choose New Query.
> 5. Run this SQL script to add a tag for testing named ANOTHER TEST TAG:
> `INSERT INTO Tag (Name) VALUES ('ANOTHER TEST TAG');`

5. When you click on the edit button of any of the tags, it should present you with a form where you can edit and save the name of the tag.
7. Try changing "ANOTHER TEST TAG" to "NOT ANOTHER A TEST TAG"
8. After saving a tag's new name, it should redirect you back to the index and the tag name you just changed should be reflected in the list of tags.
9. You can also Rerun the SQL select query under CHECK THE DATA above at any point to view the tags stored in the database and confirm that the correct TAG has been edited when testing.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- If you deleted Test Tag would it be gone from the previous ticket? So are you just recreating the same data every time?

**Comment by guacajoely** [comment]
> * If you deleted Test Tag would it be gone from the previous ticket? So are you just recreating the same data every time?

Yes. And Yes. But I have renamed it "ANOTHER TEST TAG"

**Comment by Bobbyhughes-17** [comment]
Looks fantastic!!

**Comment by Nic338** [comment]
You already merged this but I tested it and forgot to comment, sorry!

**Pull request merged**
