### PR TITLE
Ticket # 25 - Deactivate User Profiles

### PR DESCRIPTION
**Pull request by Nic338**
# Description
Completed Ticket # 25 in Trello - [Deactivate User Profiles](https://trello.com/c/AR0aUtA1/24-25-deactivate-user-profiles)
Added the ability for an admin to deactivate a user's profile, making them unable to login.
## Type of change

- [x] New feature (non-breaking change which adds functionality)

After cloning this repository to your own machine:

Download these two files [01_TabloidMVC_Create_DB.sql](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/blob/main/SQL/01_TabloidMVC_Create_DB.sql) and [02_TabloidMVC_Seed_Data.sql](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/blob/main/SQL/02_TabloidMVC_Seed_Data.sql) to create your database. Use the two links and click the Download raw file button on the right side before the code block in github starts.

In your gitbash terminal:

1. Navigate to the root directory for the repo (../tabloidmvc-yellow-belly-yackers)
2. git fetch -a
3. git checkout nm-viewuserprofiledetails
4. start TabloidMVC.sln

Once Visual Studio opens:

1. Click File > Open > File, and open the two .sql files you just downloaded.
2. Starting with the 01_TabloidMVC_Create_DB.sql, at the end of line 37, add a comma and enter down to line 38. Add the following code to line 38: `[IsActive] bit NOT NULL DEFAULT 1,` Click the green, triangular, Execute button in the top left of the screen, above where the data is entered.
3. In the 02_TabloidMVC_Seed_Data.sql file, go to line 24, and insert `[IsActive]` before the closing `)` at the end of the line. As well as on line 25, replace the code within the VALUES with `(1, 'Admina', 'Strator', 'admin', 'admin@example.com', SYSDATETIME(), NULL, 1, 1)`. 
4. After that, you are going to add some extra code into the seed data to give you a user to test this ticket on. Enter down a couple times after line 25. Now at the beginning of line 27 copy and paste this code into your code. 

`
INSERT INTO [UserProfile] (
	[Id], [FirstName], [LastName], [DisplayName], [Email], [CreateDateTime], [ImageLocation], [UserTypeId], [IsActive])
VALUES (2, 'Test', 'User', 'test', 'test@example.com', SYSDATETIME(), NULL, 2, 1);
`

5. Be sure to click the green, triangular, Execute button in the top left of the screen again after doing these steps for the seed data.
6. Click the green, triangular, button labeled TabloidMVC at the top center of your Visual Studio.

The app should launch by opening a new instance of your default web browser.

## Testing the new feature:

In the header, next to the Title (Tabloid) there should be a link to Login, click this.
For testing purposes, log in as [admin@example.com](mailto:admin@example.com), and click login.
After successfully logging in, you should now see a link to USER PROFILES, click this.
All of the profiles should be listed in alphabetical order by their Username.

You should see a list of User Profiles, with two entries. One with the name of "Admina Strator", and the other with the name of "Test User".
On the right side of the row of Test User, you should see an Edit and a Deactivate button.
Click the Deactivate button.
This will bring you to a confirmation page where you can see the user's information displayed again, and you are prompted with whether or not you would like to deactivate the user. 
Click the "Cancel Deactivation" link.
This should bring you back to the list of users once again, showing the two from before.
Click the Deactivate link again on Test User, but this time on the confirmation page click the Deactivate button.
Doing this should once again redirect you to the USER PROFILES page, except now the Deactivate option will be missing from "Test User"
Now logout from the admin@example.com user, and try to log in with the email for the Test User, test@example.com.
The app should inform you that that is an invalid email address, confirming that the user Test User, was disabled.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by guacajoely** [comment]
It was most likely user error on my part, but for some reason pasting that into the SQL query did not create a Test User for me. I manually added it just using the INSERT INTO portion of the query. I was able to deactivate the user as advertised. Great Job with a tough ticket!

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- Joel said testing instructions didn't work for him - please edit this

**Comment by Nic338** [comment]
I fixed the instructions, my data I wanted users to enter for the seed data was incorrect.

**Comment by guacajoely** [comment]
Works! Looks good!

**Comment by Bobbyhughes-17** [comment]
lOOKIN GOOD

**Review by sarahebrooks12 — APPROVED** [review]
Looks good 👼

**Pull request merged**
