### PR TITLE
Ticket #21 - Delete a comment from a post

### PR DESCRIPTION
**Pull request by gschryver**
# Description
This is on the `gs-deletecomment` branch.

For your reference: [SQL Data](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL)

**#21 Delete a Comment** in Trello - [Delete a Comment](https://trello.com/c/kE0cGypF)
Per the ticket: "As a commenter I would like the ability to remove a Comment so that I have created so that I can prevent others from seeing it in the event that I regret what I said." 

This functionality has now been implemented. 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

**GIT this branch:**
1. Clone this repository to your own machine using `git clone https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers.git`
2. `git fetch -a` in the master branch to retrieve this branch named `gs-deletecomment`.
3.  checkout this branch using the command `git checkout gs-deletecomment`

**Create the database:**
1. Open Visual Studio.
2. At the start screen select "Open a Local Folder"
4. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, then select the SQL folder
5. Run ALL THREE .sql files in the [SQL folder](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/tree/main/SQL) (The first file creates the database and tables if they don’t already exist, and the second file inserts a very small amount of sample data into those tables for testing. The third file inserts some seed data for the comments).

**Run the app:**
1. Open Visual Studio
2. At the start screen select Open a project or solution.
3. Navigate to your workspace directory, open the `tabloidmvc-yellow-belly-yackers` folder, and select the .sln file to run the solution.
7. Hit the Green play button on the toolbar that says TabloidMVC.
8. The app should launch by opening up a new window in your default browser.

**Test the new feature:**
1. Click on Log In on the navigation bar. Log in using the user: admin@example.com. 
2. Click on Posts in the navigation bar.
3. You will see a table that includes a post. Click on the "eye" icon on the right-hand side of the table (for Post Details).
4. Once inside of the post details page, you will then click on the comment bubble icon (View Comments), located below the post title, author name, publish date, edit, and delete icons.
5. This will take you to the comment details page. 
6. You will see a table that includes the username, subject, content, and create date. You should see several existing comments from the dummy data from the SQL query. **Note:** There are also links for editing and details, but those are dummy links and should not be considered at this time.
7. **NOTE**: You may create comment by using the instructions listed [here](https://github.com/NewForce-Cohort-7/tabloidmvc-yellow-belly-yackers/pull/11). Once you have created a comment, you will be taken back to the post's comment list page. Now follow the directions below.
8. Click on the blue 'Delete' link to the right of the comment in the table.
9. You will be taken to the 'Delete Comment' page. You will see in large red text: 'Are you sure you want to delete this comment?'. Below that, you will see the specific comment's subject & content. 
10. IF YOU WISH TO DELETE, you will simply press the red Delete button. Upon successful deletion, you will be taken back to the post's comments table. The comment you deleted should no longer be displayed.
11. IF YOU DO NOT WISH TO DELETE, you can also return to the previous page (post comments specified by the post ID #) by clicking on the blue, underlined 'Back to List' link.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
- If we delete the current data that is in the database, you will no longer have any data to be able to run. Can we please add more than one example? That way we are protecting out data and making sure that we can test everything for accuracy. 
- Please add more into your dummy data SQL query so we can safely delete a comment and still have some things to see

**Review by sarahebrooks12 — APPROVED** [review]
Looks great 👼

**Comment by Bobbyhughes-17** [comment]
Looks great!

**Comment by guacajoely** [comment]
looks good

**Pull request merged**
